version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon EKS...
      - aws sts get-caller-identity
      - aws eks update-kubeconfig --region us-east-2 --name fabulous-jazz-potato

  build:
    commands:
      - echo Deploying to EKS...
      - kubectl apply -f deployment.yml
