version: 0.2

phases:
  pre_build:
    commands:
      - export KUBECONFIG=/root/.kube/config
  build:
    commands:
      - echo "Deploying Kubernetes resources"
      - kubectl apply -f manifests/01-serviceaccount.yaml
      - kubectl apply -f manifests/02-clusterrolebinding.yaml
      - kubectl apply -f manifests/03-deployment.yaml
      - kubectl apply -f manifests/04-service.yaml
      - kubectl apply -f manifests/05-ingress.yaml
